### ISSUE TITLE
Standalone Mode GTK UI Sidebar becomes unresponsive within hours

### ISSUE THREAD

**Issue by dinsdalepiranha** [flathub/org.deluge_torrent.deluge#14]
As noted here:  https://dev.deluge-torrent.org/ticket/3579

Flatpak Deluge 2.1.1 (latest version, using org.gnome.Platform) - libtorrent 1.2.18.0 - Debian 11

>  Found to occur in multiple Deluge instances using "Standalone Mode" with between 61 and 1561 torrents loaded: Sidebar items in the GTK UI (View > Sidebar) become unresponsive to user input within 9 hours. This includes the items under "States" (All, Active, Downloading, Seeding, Paused, Error), "Trackers", and "Labels".
> 
> No action is required to trigger the issue and it will occur even if no new torrents are added or user input is generated.
> 
>  No relevant log output found with the `-L debug` argument specified. 

Additional output found when launching the Flatpak from CLI:

```
** (deluge:2): WARNING **: 22:11:14.232: could not allocate closure

/app/lib/python3.10/site-packages/gi/overrides/GLib.py:612: Warning: timeout_add_full: assertion 'function != NULL' failed
  return GLib.timeout_add(priority, interval, function, *user_data)
```

The above warning is from after 11 hours of the Deluge process running.

**Comment by fastrizwaan** [comment]
does this also happen to debian's `sudo apt install deluge-gtk` package too?

**Comment by dinsdalepiranha** [comment]
> does this also happen to debian's `sudo apt install deluge-gtk` package too?

That would be Deluge 2.0.3 which I don't recall exhibiting _this_ issue, but it _would_ reliably fail when attempting to migrate certain Deluge `.config/` directories from 1.3.15 (native Debian 10 version).

I can reinstall from Debian and test if necessary, but 2.0.3 is not generally suitable.  Do you happen to know if 2.0.3 will work with configs from 2.1.1?
