### ISSUE TITLE
Cursor does not change to resizing mode in KDE Plasma DE

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.deluge_torrent.deluge#4]
Steps to reproduce:
1. install Deluge from flathub on a distribution running KDE Plasma desktop environment (I'm using Arch Linux)
2. open Deluge
3. resize the sidebar, a column or the area below the torrents list

Result: you can resize in the step 3 but the cursor does not change to resizing shape

**Comment by fastrizwaan** [comment]
It is a known bug, I've reported this to deluge dev. But got no reply. https://dev.deluge-torrent.org/ticket/3468 
I don't know what's causing this. Looks more like flatpak issue with gtk.

**Comment by glaubersm** [comment]
Sad. :(
Thank you for commenting here and for reporting the bug in Deluge tracker.
