### ISSUE TITLE
CJK glyphs rendering as "glyph not found" ("tofu") characters

### ISSUE THREAD

**Issue by ssokolow** [flathub/org.deluge_torrent.deluge#6]
When I switched from the Ubuntu-packaged release of Deluge to the Flathub-packaged copy, my torrent and file names containing CJK glyphs went from rendering properly to displaying ["tofu" characters](https://en.wikipedia.org/wiki/Specials_(Unicode_block)). (i.e. Windows-style empty rectangle renderings of the `.notdef` glyph)

For example, [文字化け](https://en.wikipedia.org/wiki/Mojibake) renders as four blank rectangles.

Apparently the Deluge Flatpak is missing some fonts or font settings that are present in the AntiMicroX, Arduino IDE, Blender, Firefox, FocusWriter, Godot, JDownloader, KCachegrind, Krita, LMMS, MEGAsync, Okteta, Sweet Home 3D, Thunderbird, Tor Browser, Ungoogled Chromium, and Zeal... though Bustle, Flatseal, HandBrake, Inkscape, and jstest-gtk *do* have the same problem.

(Hopefully that list of "works here" and "doesn't work here" will help you narrow down the cause.)

Note that I'm running with a `filesystems=!xdg-download;/mnt/Seagate_10TB/flatpak-incoming/deluge:create` override to narrow the filesystem permissions so try adding that if you have trouble replicating the problem. (It's standard practice for me to install as many apps as is viable through Flatpak, use Flatseal to narrow permissions, and ensure that every application has either access to paths shared with other applications or network access but not both.)

**Comment by fastrizwaan** [comment]
I guess your system's font directory is not accessible by the sandbox deluge.
could you test it with `flatpak run --filesystem=host org.deluge_torrent.deluge`

**Comment by ssokolow** [comment]
> Sanbox can't access `/usr` ; so could you copy the fonts to `~/.fonts` directory

Judging by a lot of the ones that work, that shouldn't be necessary and, unless Flatpak special-cases `~/.fonts` (which I wouldn't want because it undermines my ability to constrain apps), shouldn't have any effect.

For example, AntiMicroX has `filesystems=!home`, resulting in `xdg-config/kdeglobals:ro` as its only grant and it still handles CJK fonts just fine.

I can still try it if you want, but it'll have to be later since I have no idea how to identify which font(s) should be copied over at the moment and I don't want to copy *all* my system fonts into `~/.fonts`.

> also please raise the issue with flatpak, as it is affecting multiple flatpak apps. https://github.com/flatpak/flatpak/issues

Thanks. I'll do so after I've gotten some more urgent TODOs out of the way.

Since opening this bug, it occurred to me that it might be a bug in the GNOME runtime, but both Deluge (which has the problem) and Sweet Home 3D (which does not) are using `org.freedesktop.Platform` version 20.08, leaving "GTK under Flatpak" as the only obvious commonality between all the programs which aren't working.

**Comment by fastrizwaan** [comment]
issue still there, updated to 23.08?

**Comment by ssokolow** [comment]
I got tired of waking up to find that Deluge's backend had become non-responsive during the night and replaced it with the KTorrent Flatpak a couple of weeks ago. (With the added plus that I no longer have to deal with GTK3's context menu shadows becoming giant boxes whenever I fullscreen MPV on another monitor and it suspends compositing.)

**Comment by fastrizwaan** [comment]
OK. closing.
